name: Testing

on: [push]

jobs:
  miniconda:
    name: Miniconda ${{ matrix.os }} Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Edit environment.yml file
        shell: bash -l {0}
        run: |
          sed -i 's/  - python=3.10//' environment.yml
      - name: Set up Conda with Python ${{ matrix.python-version }} and dependencies
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ReausoKit
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: True
      - name: Print Conda Information
        shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Test with pytest
        shell: bash -l {0}
        run: |
          conda install pytest
          pytest
