name: Testing

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        environment: [ test ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment ${{ matrix.environment }}
        uses: prefix-dev/setup-pixi@v0.8.3
        with:
          environments: ${{ matrix.environment }}
          cache: false
      - name: Print Pixi Information
        shell: bash -l {0}
        run: |
          pixi info
          pixi list
      - name: Test with pixi run test
        shell: bash -l {0}
        run: |
          pixi run test
