name: Testing

on: [push]

jobs:
  miniconda:
    name: Miniconda ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Conda with Python 3.10 and dependencies
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ReausoKit
          environment-file: environment.yml
          python-version: 3.10
          auto-activate-base: false
      - name: Test with pytest
        run: |
          conda install pytest
          pytest
